---
hostname: SW0

vlans: "{{ vlans_external }}"

default_gateway: 10.0.0.18

l2_interfaces:
  - name: "{{ sInt['Fa0/1'] }}"
    description: "Trunk Zabreg"
    trunk:
      native_vlan: 1
      allowed_vlans: "6,102,103"
  
  - name: "{{ sInt['Fa0/2'] }}"
    description: "Trunk Pula"
    trunk:      
      native_vlan: 1
      allowed_vlans: "6,102,203"
  
  - name: "{{ sInt['Fa0/3'] }}"
    description: "Trunk Split"
    trunk:
      native_vlan: 1
      allowed_vlans: "6,103,203"
  
  - name: "{{ sInt['Fa0/4'] }}"
    description: "Ansible"
    access:
      vlan: 6

svis:
  - vlan_id: 6
    description: "Management Interface"
    ipv4:
      address: 10.0.0.13
      prefix: 29
    ipv6:
      address: "FE80::6:1"
      link_local: True

unused_interfaces_real:
  - "{{ sInt['Fa0/5'] }}"
  - "{{ sInt['Fa0/6'] }}"
  - "{{ sInt['Fa0/7'] }}"
  - "{{ sInt['Fa0/8'] }}"
  - "{{ sInt['Fa0/9'] }}"
  - "{{ sInt['Fa0/10'] }}"
  - "{{ sInt['Fa0/11'] }}"
  - "{{ sInt['Fa0/12'] }}"
  - "{{ sInt['Fa0/13'] }}"
  - "{{ sInt['Fa0/14'] }}"
  - "{{ sInt['Fa0/15'] }}"
  - "{{ sInt['Fa0/16'] }}"
  - "{{ sInt['Fa0/17'] }}"
  - "{{ sInt['Fa0/18'] }}"
  - "{{ sInt['Fa0/19'] }}"
  - "{{ sInt['Fa0/20'] }}"
  - "{{ sInt['Fa0/21'] }}"
  - "{{ sInt['Fa0/22'] }}"
  - "{{ sInt['Fa0/23'] }}"
  - "{{ sInt['Fa0/24'] }}"
  - "{{ sInt['Gig0/1'] }}"
  - "{{ sInt['Gig0/2'] }}"