# =============================================
# FILE: inventory.yml
# =============================================
---
all:
  children:

    layer3:
      children:
        routers:
          hosts:
            RT1-Zg:
              ansible_host: 10.0.0.18
            RT1-Pl:
              ansible_host: 10.0.0.19
            RT1-St:
              ansible_host: 10.0.0.20

        servers:
          hosts:
            DHCP-SRV:
              ansible_host: 172.20.0.196

    layer23:
      children:
        mls:
          hosts:
            MLS1-Zg:
              ansible_host: 172.20.0.158
            MLS2-Zg:
              ansible_host: 172.20.0.154

    layer2:
      children:
        access_switches:
          hosts:
            SW1-Zg:
              ansible_host: 172.20.0.228
            SW2-Zg:
              ansible_host: 172.20.0.229
            SW1-Pl:
              ansible_host: 172.20.8.146
            SW1-St:
              ansible_host: 172.20.12.18

        wan_switches:
          hosts:
            SW0:
              ansible_host: 10.0.0.17

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_ssh_common_args: '-o Ciphers=+aes256-cbc -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa'
    ansible_user: cisco
    ansible_password: "classclass"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "classclass"
